### ISSUE TITLE
用本地版本代码跑

### ISSUE THREAD

**Issue by isgbuddy** [Jack-Cherish/quantitative#1]
第一天应该什么时候建仓？是不是 "今日择时信号: " 是 BUY 的时候开始建仓？

**Comment by isgbuddy** [comment]
跑本地的 get_test，怎么得到所有信息都是 SELL，是不是程序有 Bugs?

**Comment by Jack-Cherish** [comment]
微信应该已回复

**Comment by isgbuddy** [comment]
> 微信应该已回复

跑你的  get_test，回测 30 天，每天的 get_rank 返回值都一样！

` pandas 版本高于 0.25，get_price 与 get_fundamentals_continuously 接口的 panel 参数将固定为 False（0.25 及以上版本的 pandas 不再支持 panel，如使用该数据结构和相关函数请注意修改）
  warnings.warn(PandasChecker.VERSION_NOTICE_MESSAGE, PanelObsoleteWarning)
29 2021-08-18 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
28 2021-08-19 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
27 2021-08-20 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
26 2021-08-21 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
25 2021-08-22 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
24 2021-08-23 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
23 2021-08-24 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
22 2021-08-25 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
21 2021-08-26 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
20 2021-08-27 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
19 2021-08-28 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
18 2021-08-29 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
17 2021-08-30 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
16 2021-08-31 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
15 2021-09-01 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
14 2021-09-02 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
13 2021-09-03 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
12 2021-09-04 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
11 2021-09-05 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
10 2021-09-06 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
9 2021-09-07 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
8 2021-09-08 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
7 2021-09-09 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
6 2021-09-10 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
5 2021-09-11 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
4 2021-09-12 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
3 2021-09-13 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
2 2021-09-14 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************
1 2021-09-15 00:00:00
##############################候选##############################
500ETF(510500.XSHG):1.124720074553465
300ETF(510300.XSHG):-2.3313729349043594e-06
创业板ETF易方达(159915.XSHE):-0.3320559874800206
################################################################
今日自选股:500ETF(510500.XSHG)
今日择时信号:KEEP
****************************************************************************************************

Process finished with exit code 0
`
